version: 0.0
os: linux
files:
  - source: 
    destination: 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location:
      timeout:
      runas:
  ApplicationStart:
    - location:
      timeout:
      runas:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

